config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get '/dashboard' => 'dashboard#index'
  resources :suppliers do
    resources :items
  end
  resources :purchases
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :supplier
  has_and_belongs_to_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  has_and_belongs_to_many :items
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @suppliers = Supplier.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_supplier
  before_action :find_item, except: [:new, :create]

  def new
    @item = @supplier.items.build
  end

  def show; end

  def create
    @item = @supplier.items.new(item_params)
    if @item.save
      flash[:notice] = 'You have successfully added an item!'
      redirect_to supplier_path(@supplier)
    else
      flash[:alert] = ''
      supplier.errors.each do |key, value|
        flash[:alert] += "#{key}: #{value}"
      end
      redirect_to new_supplier_item_path
    end
  end

  def edit; end

  def update
    @item.update(item_params)
    redirect_to supplier_path(@supplier)
  end

  def destroy
    @item.delete
    redirect_to supplier_path(@supplier)
  end

  private

  def item_params
    params.require(:item).permit(:name, :product_code, :description, :quantity, :price)
  end

  def find_supplier
    @supplier = Supplier.find(params[:supplier_id])
  end

  def find_item
    @item = @supplier.items.find(params[:id])
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :find_supplier, except: [:new, :create]

  def new
    @supplier = Supplier.new
  end

  def create
    supplier = Supplier.new(supplier_params)
    if supplier.save
      flash[:notice] = 'You have successfully added a supplier!'
      redirect_to dashboard_url
    else
      flash[:alert] = ''
      supplier.errors.each do |key, value|
        flash[:alert] += "#{key}: #{value}"
      end
      redirect_to new_supplier_url
    end
  end

  def show
    @items = @supplier.items
  end

  def edit; end

  def update
    @supplier.update(supplier_params)
    redirect_to dashboard_url
  end

  def destroy
    @supplier.delete
    redirect_to dashboard_url
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :email, :website, :phone)
  end

  def find_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard of Radiko</h1>

<% if user_signed_in? %>
  <h3>Signed in as <%= current_user.first_name %> <%= current_user.last_name %></h3>
<% end %>

<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
<%= link_to 'Add Supplier', new_supplier_path %>
<%= link_to 'Create Purchase', new_purchase_path %>

<% @suppliers.each do |supplier| %>
  <div>Name: <%= link_to supplier.name, supplier_path(supplier) %></div>
  <div>Email: <%= supplier.email %></div>
  <div>Phone: <%= supplier.phone %></div>
  <div>Website: <%= supplier.website %></div>
  <%= link_to 'Edit', edit_supplier_path(supplier) %>
  <%= link_to 'Delete', supplier_path(supplier), data: { confirm: 'Are you sure?', method: :delete } %>
<% end %>

app/views/items/_form.html.erb
<%= form_for [@supplier, @item]  do |f| %>
  Name: <%= f.text_field :name %><br />
  Product code: <%= f.text_field :product_code %><br />
  Description: <%= f.text_field :description %><br />
  Quantity: <%= f.number_field :quantity %><br />
  Price: <%= f.number_field :price %><br />
  <%= f.submit 'Submit' %>
<% end %>

<%= link_to 'Supplier', supplier_path(@supplier) %>
<%= link_to 'Dashboard', dashboard_path %>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= render 'form' %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<%= link_to 'Supplier', supplier_path(@supplier) %>
<%= link_to 'Dashboard', dashboard_path %>

<div>Name: <%= @item.name %></div>
<div>Product code: <%= @item.product_code %></div>
<div>Description: <%= @item.description %></div>
<div>Quantity: <%= @item.quantity %></div>
<div>Price: <%= @item.price %></div>

<%= link_to 'Edit', edit_supplier_item_path(@supplier, @item) %>
<%= link_to 'Delete', supplier_item_path(@supplier, @item), data: { confirm: 'Are you sure?', method: :delete } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RadikoPurchase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

app/views/suppliers/_form.html.erb
<%= form_for @supplier  do |f| %>
  Name: <%= f.text_field :name %><br />
  Email: <%= f.email_field :email %><br />
  Phone: <%= f.text_field :phone %><br />
  Website: <%= f.text_field :website %><br />
  <%= f.submit 'Submit' %>
<% end %>

<%= link_to 'Dashboard', dashboard_path %>

app/views/suppliers/edit.html.erb
<h1>Edit supplier</h1>

<%= render 'form' %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<div>Name: <%= @supplier.name %></div>
<div>Email: <%= @supplier.email %></div>
<div>Phone: <%= @supplier.phone %></div>
<div>Website: <%= @supplier.website %></div>

<%= link_to 'Edit', edit_supplier_path(@supplier) %>
<%= link_to 'Delete', supplier_path(@supplier), data: { confirm: 'Are you sure?', method: :delete } %>
<%= link_to 'Dashboard', dashboard_path %>
<%= link_to 'Add Item', new_supplier_item_path(@supplier) %>

<h2>Items</h2>
<% @items.each do |item| %>
  <div>Name: <%= link_to item.name, supplier_item_path(@supplier, item) %></div>
  <div>Product code: <%= item.product_code %></div>
  <div>Description: <%= item.description %></div>
  <div>Quantity: <%= item.quantity %></div>
  <div>Price: <%= item.price %></div>
  <%= link_to 'Edit', edit_supplier_item_path(@supplier, item) %>
  <%= link_to 'Delete', supplier_item_path(@supplier, item), data: { confirm: 'Are you sure?', method: :delete } %>
<% end %>